framework:
    mailer:
        envelope:
            sender: 'Awesome system <no-reply@hotmail.com>'
        headers:
            From: 'Awesome system <no-reply@hotmail.com>'
        dsn: '%env(MAILER_DSN)%'
